/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_User_add (void)
{
  GtkWidget *User_add;
  GtkWidget *fixed1;
  GtkWidget *entry1_ali;
  GtkWidget *entry2_ali;
  GtkWidget *label62;
  GtkWidget *label63;
  GtkWidget *button1_ali;
  GtkWidget *alignment22;
  GtkWidget *hbox22;
  GtkWidget *image37;
  GtkWidget *label61;
  GtkWidget *label1;
  GtkWidget *image38;
  GtkWidget *image36;

  User_add = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (User_add), _("User_add"));

  fixed1 = gtk_fixed_new ();
  gtk_widget_show (fixed1);
  gtk_container_add (GTK_CONTAINER (User_add), fixed1);

  entry1_ali = gtk_entry_new ();
  gtk_widget_show (entry1_ali);
  gtk_fixed_put (GTK_FIXED (fixed1), entry1_ali, 160, 88);
  gtk_widget_set_size_request (entry1_ali, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry1_ali), 8226);

  entry2_ali = gtk_entry_new ();
  gtk_widget_show (entry2_ali);
  gtk_fixed_put (GTK_FIXED (fixed1), entry2_ali, 160, 144);
  gtk_widget_set_size_request (entry2_ali, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry2_ali), 8226);

  label62 = gtk_label_new (_("<span color=\"LIGHTSEAGREEN\"font='11'weight='bold'>Login :</span>"));
  gtk_widget_show (label62);
  gtk_fixed_put (GTK_FIXED (fixed1), label62, 8, 88);
  gtk_widget_set_size_request (label62, 136, 24);
  gtk_label_set_use_markup (GTK_LABEL (label62), TRUE);

  label63 = gtk_label_new (_("<span color=\"LIGHTSEAGREEN\"font='11'weight='bold'>Mot de passe :</span>"));
  gtk_widget_show (label63);
  gtk_fixed_put (GTK_FIXED (fixed1), label63, 16, 152);
  gtk_widget_set_size_request (label63, 112, 16);
  gtk_label_set_use_markup (GTK_LABEL (label63), TRUE);

  button1_ali = gtk_button_new ();
  gtk_widget_show (button1_ali);
  gtk_fixed_put (GTK_FIXED (fixed1), button1_ali, 344, 200);
  gtk_widget_set_size_request (button1_ali, 104, 29);

  alignment22 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment22);
  gtk_container_add (GTK_CONTAINER (button1_ali), alignment22);

  hbox22 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox22);
  gtk_container_add (GTK_CONTAINER (alignment22), hbox22);

  image37 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image37);
  gtk_box_pack_start (GTK_BOX (hbox22), image37, FALSE, FALSE, 0);

  label61 = gtk_label_new_with_mnemonic (_(" Confirmer"));
  gtk_widget_show (label61);
  gtk_box_pack_start (GTK_BOX (hbox22), label61, FALSE, FALSE, 0);

  label1 = gtk_label_new (_("<span foreground=\"#900000\"\nfont_desc=\"bold 15\"\nvariant=\"smallcaps\">Bienvenue !  </span>"));
  gtk_widget_show (label1);
  gtk_fixed_put (GTK_FIXED (fixed1), label1, 192, 16);
  gtk_widget_set_size_request (label1, 128, 31);
  gtk_label_set_use_markup (GTK_LABEL (label1), TRUE);

  image38 = create_pixmap (User_add, "tn.png");
  gtk_widget_show (image38);
  gtk_fixed_put (GTK_FIXED (fixed1), image38, 32, 8);
  gtk_widget_set_size_request (image38, 64, 56);
  gtk_misc_set_alignment (GTK_MISC (image38), 0.5, 0);

  image36 = create_pixmap (User_add, "index.png");
  gtk_widget_show (image36);
  gtk_fixed_put (GTK_FIXED (fixed1), image36, 368, 8);
  gtk_widget_set_size_request (image36, 72, 56);
  gtk_misc_set_alignment (GTK_MISC (image36), 0.71, 0.71);

  g_signal_connect ((gpointer) button1_ali, "clicked",
                    G_CALLBACK (on_button1_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (User_add, User_add, "User_add");
  GLADE_HOOKUP_OBJECT (User_add, fixed1, "fixed1");
  GLADE_HOOKUP_OBJECT (User_add, entry1_ali, "entry1_ali");
  GLADE_HOOKUP_OBJECT (User_add, entry2_ali, "entry2_ali");
  GLADE_HOOKUP_OBJECT (User_add, label62, "label62");
  GLADE_HOOKUP_OBJECT (User_add, label63, "label63");
  GLADE_HOOKUP_OBJECT (User_add, button1_ali, "button1_ali");
  GLADE_HOOKUP_OBJECT (User_add, alignment22, "alignment22");
  GLADE_HOOKUP_OBJECT (User_add, hbox22, "hbox22");
  GLADE_HOOKUP_OBJECT (User_add, image37, "image37");
  GLADE_HOOKUP_OBJECT (User_add, label61, "label61");
  GLADE_HOOKUP_OBJECT (User_add, label1, "label1");
  GLADE_HOOKUP_OBJECT (User_add, image38, "image38");
  GLADE_HOOKUP_OBJECT (User_add, image36, "image36");

  return User_add;
}

GtkWidget*
create_Espace_admin (void)
{
  GtkWidget *Espace_admin;
  GtkWidget *fixed2;
  GtkWidget *button3_ajouter3;
  GtkWidget *alignment1;
  GtkWidget *hbox1;
  GtkWidget *image1;
  GtkWidget *label8;
  GtkWidget *image29;
  GtkWidget *button5_supprimer5;
  GtkWidget *alignment3;
  GtkWidget *hbox3;
  GtkWidget *image3;
  GtkWidget *label10;
  GtkWidget *label7;
  GtkWidget *image35;
  GtkWidget *button4_modifier4;
  GtkWidget *alignment2;
  GtkWidget *hbox2;
  GtkWidget *image2;
  GtkWidget *label9;

  Espace_admin = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (Espace_admin), _("Espace_admin"));

  fixed2 = gtk_fixed_new ();
  gtk_widget_show (fixed2);
  gtk_container_add (GTK_CONTAINER (Espace_admin), fixed2);

  button3_ajouter3 = gtk_button_new ();
  gtk_widget_show (button3_ajouter3);
  gtk_fixed_put (GTK_FIXED (fixed2), button3_ajouter3, 112, 88);
  gtk_widget_set_size_request (button3_ajouter3, 224, 29);

  alignment1 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment1);
  gtk_container_add (GTK_CONTAINER (button3_ajouter3), alignment1);

  hbox1 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox1);
  gtk_container_add (GTK_CONTAINER (alignment1), hbox1);

  image1 = gtk_image_new_from_stock ("gtk-network", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image1);
  gtk_box_pack_start (GTK_BOX (hbox1), image1, FALSE, FALSE, 0);

  label8 = gtk_label_new_with_mnemonic (_(" G\303\251rer les parkings"));
  gtk_widget_show (label8);
  gtk_box_pack_start (GTK_BOX (hbox1), label8, FALSE, FALSE, 0);

  image29 = create_pixmap (Espace_admin, "tn.png");
  gtk_widget_show (image29);
  gtk_fixed_put (GTK_FIXED (fixed2), image29, 16, 8);
  gtk_widget_set_size_request (image29, 64, 56);
  gtk_misc_set_alignment (GTK_MISC (image29), 0.5, 0);

  button5_supprimer5 = gtk_button_new ();
  gtk_widget_show (button5_supprimer5);
  gtk_fixed_put (GTK_FIXED (fixed2), button5_supprimer5, 112, 184);
  gtk_widget_set_size_request (button5_supprimer5, 224, 29);

  alignment3 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment3);
  gtk_container_add (GTK_CONTAINER (button5_supprimer5), alignment3);

  hbox3 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox3);
  gtk_container_add (GTK_CONTAINER (alignment3), hbox3);

  image3 = gtk_image_new_from_stock ("gtk-dialog-authentication", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image3);
  gtk_box_pack_start (GTK_BOX (hbox3), image3, FALSE, FALSE, 0);

  label10 = gtk_label_new_with_mnemonic (_(" G\303\251rer les agents"));
  gtk_widget_show (label10);
  gtk_box_pack_start (GTK_BOX (hbox3), label10, FALSE, FALSE, 0);

  label7 = gtk_label_new (_("<span foreground=\"#900000\"\nfont_desc=\"bold 15\"\nvariant=\"smallcaps\"> S\303\251l\303\251ctionner votre choix : </span>"));
  gtk_widget_show (label7);
  gtk_fixed_put (GTK_FIXED (fixed2), label7, 96, 24);
  gtk_widget_set_size_request (label7, 272, 32);
  gtk_label_set_use_markup (GTK_LABEL (label7), TRUE);

  image35 = create_pixmap (Espace_admin, "index.png");
  gtk_widget_show (image35);
  gtk_fixed_put (GTK_FIXED (fixed2), image35, 376, 8);
  gtk_widget_set_size_request (image35, 72, 56);
  gtk_misc_set_alignment (GTK_MISC (image35), 0.71, 0.71);

  button4_modifier4 = gtk_button_new ();
  gtk_widget_show (button4_modifier4);
  gtk_fixed_put (GTK_FIXED (fixed2), button4_modifier4, 112, 136);
  gtk_widget_set_size_request (button4_modifier4, 224, 29);

  alignment2 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment2);
  gtk_container_add (GTK_CONTAINER (button4_modifier4), alignment2);

  hbox2 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox2);
  gtk_container_add (GTK_CONTAINER (alignment2), hbox2);

  image2 = gtk_image_new_from_stock ("gtk-preferences", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image2);
  gtk_box_pack_start (GTK_BOX (hbox2), image2, FALSE, FALSE, 0);

  label9 = gtk_label_new_with_mnemonic (_(" G\303\251rer les services"));
  gtk_widget_show (label9);
  gtk_box_pack_start (GTK_BOX (hbox2), label9, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) button3_ajouter3, "clicked",
                    G_CALLBACK (on_button3_ajouter3_clicked),
                    NULL);
  g_signal_connect ((gpointer) button5_supprimer5, "clicked",
                    G_CALLBACK (on_button5_supprimer5_clicked),
                    NULL);
  g_signal_connect ((gpointer) button4_modifier4, "clicked",
                    G_CALLBACK (on_button4_modifier4_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (Espace_admin, Espace_admin, "Espace_admin");
  GLADE_HOOKUP_OBJECT (Espace_admin, fixed2, "fixed2");
  GLADE_HOOKUP_OBJECT (Espace_admin, button3_ajouter3, "button3_ajouter3");
  GLADE_HOOKUP_OBJECT (Espace_admin, alignment1, "alignment1");
  GLADE_HOOKUP_OBJECT (Espace_admin, hbox1, "hbox1");
  GLADE_HOOKUP_OBJECT (Espace_admin, image1, "image1");
  GLADE_HOOKUP_OBJECT (Espace_admin, label8, "label8");
  GLADE_HOOKUP_OBJECT (Espace_admin, image29, "image29");
  GLADE_HOOKUP_OBJECT (Espace_admin, button5_supprimer5, "button5_supprimer5");
  GLADE_HOOKUP_OBJECT (Espace_admin, alignment3, "alignment3");
  GLADE_HOOKUP_OBJECT (Espace_admin, hbox3, "hbox3");
  GLADE_HOOKUP_OBJECT (Espace_admin, image3, "image3");
  GLADE_HOOKUP_OBJECT (Espace_admin, label10, "label10");
  GLADE_HOOKUP_OBJECT (Espace_admin, label7, "label7");
  GLADE_HOOKUP_OBJECT (Espace_admin, image35, "image35");
  GLADE_HOOKUP_OBJECT (Espace_admin, button4_modifier4, "button4_modifier4");
  GLADE_HOOKUP_OBJECT (Espace_admin, alignment2, "alignment2");
  GLADE_HOOKUP_OBJECT (Espace_admin, hbox2, "hbox2");
  GLADE_HOOKUP_OBJECT (Espace_admin, image2, "image2");
  GLADE_HOOKUP_OBJECT (Espace_admin, label9, "label9");

  return Espace_admin;
}

GtkWidget*
create_Sur (void)
{
  GtkWidget *Sur;
  GtkWidget *fixed7;
  GtkWidget *radiobutton2_supp_ann;
  GSList *radiobutton2_supp_ann_group = NULL;
  GtkWidget *radiobutton1_supp_conf;
  GtkWidget *alibouaine_label17;
  GtkWidget *alibouaine_button10;
  GtkWidget *alignment23;
  GtkWidget *hbox23;
  GtkWidget *image39;
  GtkWidget *label64;

  Sur = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (Sur), _("Sur"));

  fixed7 = gtk_fixed_new ();
  gtk_widget_show (fixed7);
  gtk_container_add (GTK_CONTAINER (Sur), fixed7);

  radiobutton2_supp_ann = gtk_radio_button_new_with_mnemonic (NULL, _("Annuler"));
  gtk_widget_show (radiobutton2_supp_ann);
  gtk_fixed_put (GTK_FIXED (fixed7), radiobutton2_supp_ann, 128, 112);
  gtk_widget_set_size_request (radiobutton2_supp_ann, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton2_supp_ann), radiobutton2_supp_ann_group);
  radiobutton2_supp_ann_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton2_supp_ann));

  radiobutton1_supp_conf = gtk_radio_button_new_with_mnemonic (NULL, _("Supprimer"));
  gtk_widget_show (radiobutton1_supp_conf);
  gtk_fixed_put (GTK_FIXED (fixed7), radiobutton1_supp_conf, 128, 72);
  gtk_widget_set_size_request (radiobutton1_supp_conf, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton1_supp_conf), radiobutton2_supp_ann_group);
  radiobutton2_supp_ann_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton1_supp_conf));

  alibouaine_label17 = gtk_label_new (_("<span foreground=\"#900000\"\nfont_desc=\"bold 15\"\nvariant=\"smallcaps\">Etes-vous sur de votre r\303\251ponse !?  </span>"));
  gtk_widget_show (alibouaine_label17);
  gtk_fixed_put (GTK_FIXED (fixed7), alibouaine_label17, 8, 16);
  gtk_widget_set_size_request (alibouaine_label17, 320, 24);
  gtk_label_set_use_markup (GTK_LABEL (alibouaine_label17), TRUE);

  alibouaine_button10 = gtk_button_new ();
  gtk_widget_show (alibouaine_button10);
  gtk_fixed_put (GTK_FIXED (fixed7), alibouaine_button10, 248, 152);
  gtk_widget_set_size_request (alibouaine_button10, 90, 29);

  alignment23 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment23);
  gtk_container_add (GTK_CONTAINER (alibouaine_button10), alignment23);

  hbox23 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox23);
  gtk_container_add (GTK_CONTAINER (alignment23), hbox23);

  image39 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image39);
  gtk_box_pack_start (GTK_BOX (hbox23), image39, FALSE, FALSE, 0);

  label64 = gtk_label_new_with_mnemonic (_("Valider"));
  gtk_widget_show (label64);
  gtk_box_pack_start (GTK_BOX (hbox23), label64, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) radiobutton2_supp_ann, "toggled",
                    G_CALLBACK (on_radiobutton2_supp_ann_toggled),
                    NULL);
  g_signal_connect ((gpointer) radiobutton1_supp_conf, "toggled",
                    G_CALLBACK (on_radiobutton1_supp_conf_toggled),
                    NULL);
  g_signal_connect ((gpointer) alibouaine_button10, "clicked",
                    G_CALLBACK (on_button10_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (Sur, Sur, "Sur");
  GLADE_HOOKUP_OBJECT (Sur, fixed7, "fixed7");
  GLADE_HOOKUP_OBJECT (Sur, radiobutton2_supp_ann, "radiobutton2_supp_ann");
  GLADE_HOOKUP_OBJECT (Sur, radiobutton1_supp_conf, "radiobutton1_supp_conf");
  GLADE_HOOKUP_OBJECT (Sur, alibouaine_label17, "alibouaine_label17");
  GLADE_HOOKUP_OBJECT (Sur, alibouaine_button10, "alibouaine_button10");
  GLADE_HOOKUP_OBJECT (Sur, alignment23, "alignment23");
  GLADE_HOOKUP_OBJECT (Sur, hbox23, "hbox23");
  GLADE_HOOKUP_OBJECT (Sur, image39, "image39");
  GLADE_HOOKUP_OBJECT (Sur, label64, "label64");

  return Sur;
}

GtkWidget*
create_Services (void)
{
  GtkWidget *Services;
  GtkWidget *alibouaine_notebook1;
  GtkWidget *alibouaine_fixed10;
  GtkWidget *alibouaine_entry9;
  GtkWidget *alibouaine_entry10;
  GtkWidget *alibouaine_label38;
  GtkWidget *alibouaine_label39;
  GtkWidget *image24;
  GtkWidget *image28;
  GtkWidget *alibouaine_label51;
  GtkWidget *alibouaine_label36;
  GtkWidget *alibouaine_label37;
  GtkObject *spinbutton1_ali_adj;
  GtkWidget *spinbutton1_ali;
  GtkWidget *ali_button3;
  GtkWidget *alignment26;
  GtkWidget *hbox26;
  GtkWidget *image44;
  GtkWidget *label68;
  GtkWidget *alibouaine_checkbutton10;
  GtkWidget *alibouaine_checkbutton9;
  GtkWidget *alibouaine_label31;
  GtkWidget *alibouaine_fixed11;
  GtkObject *alibouaine_spinbutton4_adj;
  GtkWidget *alibouaine_spinbutton4;
  GtkWidget *alibouaine_entry11;
  GtkWidget *alibouaine_entry12;
  GtkWidget *alibouaine_label42;
  GtkWidget *alibouaine_label43;
  GtkWidget *alibouaine_label52;
  GtkWidget *image23;
  GtkWidget *image27;
  GtkWidget *alibouaine_label41;
  GtkWidget *alibouaine_label40;
  GtkWidget *ali_button4;
  GtkWidget *alignment27;
  GtkWidget *hbox27;
  GtkWidget *image45;
  GtkWidget *label69;
  GtkWidget *alibouaine_checkbutton12;
  GtkWidget *alibouaine_checkbutton11;
  GtkWidget *ali_label32;
  GtkWidget *alibouaine_fixed13;
  GtkObject *alibouaine_spinbutton5_adj;
  GtkWidget *alibouaine_spinbutton5;
  GtkWidget *image22;
  GtkWidget *image26;
  GtkWidget *alibouaine_label53;
  GtkWidget *alibouaine_label44;
  GtkWidget *ali_label71;
  GtkWidget *alibouaine_button17;
  GtkWidget *alignment7;
  GtkWidget *hbox7;
  GtkWidget *image12;
  GtkWidget *label45;
  GtkWidget *alibouaine_label33;
  GtkWidget *alibouaine_fixed12;
  GtkWidget *alibouaine_treeview1;
  GtkWidget *image21;
  GtkWidget *image25;
  GtkWidget *alibouaine_label46;
  GtkWidget *ali_button5;
  GtkWidget *alignment28;
  GtkWidget *hbox28;
  GtkWidget *image46;
  GtkWidget *label70;
  GtkWidget *alibouaine_abel34;
  GtkWidget *alibouaine_fixed14;
  GtkWidget *alibouaine_combobox2;
  GtkObject *alibouaine_spinbutton6_adj;
  GtkWidget *alibouaine_spinbutton6;
  GtkWidget *alibouaine_textview2;
  GtkWidget *alibouaine_label48;
  GtkWidget *alibouaine_label50;
  GtkWidget *alibouaine_label54;
  GtkWidget *alibouaine_label47;
  GtkWidget *image19;
  GtkWidget *image20;
  GtkWidget *ali_button18;
  GtkWidget *alignment8;
  GtkWidget *hbox8;
  GtkWidget *image13;
  GtkWidget *label49;
  GtkWidget *alibouaine_label35;

  Services = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (Services), _("Services"));

  alibouaine_notebook1 = gtk_notebook_new ();
  gtk_widget_show (alibouaine_notebook1);
  gtk_container_add (GTK_CONTAINER (Services), alibouaine_notebook1);

  alibouaine_fixed10 = gtk_fixed_new ();
  gtk_widget_show (alibouaine_fixed10);
  gtk_container_add (GTK_CONTAINER (alibouaine_notebook1), alibouaine_fixed10);

  alibouaine_entry9 = gtk_entry_new ();
  gtk_widget_show (alibouaine_entry9);
  gtk_fixed_put (GTK_FIXED (alibouaine_fixed10), alibouaine_entry9, 224, 136);
  gtk_widget_set_size_request (alibouaine_entry9, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (alibouaine_entry9), 8226);

  alibouaine_entry10 = gtk_entry_new ();
  gtk_widget_show (alibouaine_entry10);
  gtk_fixed_put (GTK_FIXED (alibouaine_fixed10), alibouaine_entry10, 224, 192);
  gtk_widget_set_size_request (alibouaine_entry10, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (alibouaine_entry10), 8226);

  alibouaine_label38 = gtk_label_new (_("<span color=\"LIGHTSEAGREEN\"font='11'weight='bold'>Le prix du service\n       (en dinars) :</span>"));
  gtk_widget_show (alibouaine_label38);
  gtk_fixed_put (GTK_FIXED (alibouaine_fixed10), alibouaine_label38, 16, 184);
  gtk_widget_set_size_request (alibouaine_label38, 136, 32);
  gtk_label_set_use_markup (GTK_LABEL (alibouaine_label38), TRUE);

  alibouaine_label39 = gtk_label_new (_("<span color=\"LIGHTSEAGREEN\"font='11'weight='bold'>Les modes de paiement\n        disponibles :</span>"));
  gtk_widget_show (alibouaine_label39);
  gtk_fixed_put (GTK_FIXED (alibouaine_fixed10), alibouaine_label39, 8, 256);
  gtk_widget_set_size_request (alibouaine_label39, 216, 48);
  gtk_label_set_use_markup (GTK_LABEL (alibouaine_label39), TRUE);

  image24 = create_pixmap (Services, "index.png");
  gtk_widget_show (image24);
  gtk_fixed_put (GTK_FIXED (alibouaine_fixed10), image24, 544, 8);
  gtk_widget_set_size_request (image24, 72, 56);
  gtk_misc_set_alignment (GTK_MISC (image24), 0.71, 0.71);

  image28 = create_pixmap (Services, "tn.png");
  gtk_widget_show (image28);
  gtk_fixed_put (GTK_FIXED (alibouaine_fixed10), image28, 56, 0);
  gtk_widget_set_size_request (image28, 64, 56);
  gtk_misc_set_alignment (GTK_MISC (image28), 0.5, 0);

  alibouaine_label51 = gtk_label_new (_("<span foreground=\"#900000\"\nfont_desc=\"bold 15\"\nvariant=\"smallcaps\"> Ajouter un service : </span>"));
  gtk_widget_show (alibouaine_label51);
  gtk_fixed_put (GTK_FIXED (alibouaine_fixed10), alibouaine_label51, 216, 16);
  gtk_widget_set_size_request (alibouaine_label51, 216, 24);
  gtk_label_set_use_markup (GTK_LABEL (alibouaine_label51), TRUE);

  alibouaine_label36 = gtk_label_new (_("<span color=\"LIGHTSEAGREEN\"font='11'weight='bold'>Id service :</span>"));
  gtk_widget_show (alibouaine_label36);
  gtk_fixed_put (GTK_FIXED (alibouaine_fixed10), alibouaine_label36, 40, 88);
  gtk_widget_set_size_request (alibouaine_label36, 88, 17);
  gtk_label_set_use_markup (GTK_LABEL (alibouaine_label36), TRUE);

  alibouaine_label37 = gtk_label_new (_("<span color=\"LIGHTSEAGREEN\"font='11'weight='bold'>Le service :</span>"));
  gtk_widget_show (alibouaine_label37);
  gtk_fixed_put (GTK_FIXED (alibouaine_fixed10), alibouaine_label37, 40, 136);
  gtk_widget_set_size_request (alibouaine_label37, 80, 16);
  gtk_label_set_use_markup (GTK_LABEL (alibouaine_label37), TRUE);

  spinbutton1_ali_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  spinbutton1_ali = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton1_ali_adj), 1, 0);
  gtk_widget_show (spinbutton1_ali);
  gtk_fixed_put (GTK_FIXED (alibouaine_fixed10), spinbutton1_ali, 224, 88);
  gtk_widget_set_size_request (spinbutton1_ali, 160, 27);

  ali_button3 = gtk_button_new ();
  gtk_widget_show (ali_button3);
  gtk_fixed_put (GTK_FIXED (alibouaine_fixed10), ali_button3, 560, 320);
  gtk_widget_set_size_request (ali_button3, 106, 29);

  alignment26 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment26);
  gtk_container_add (GTK_CONTAINER (ali_button3), alignment26);

  hbox26 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox26);
  gtk_container_add (GTK_CONTAINER (alignment26), hbox26);

  image44 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image44);
  gtk_box_pack_start (GTK_BOX (hbox26), image44, FALSE, FALSE, 0);

  label68 = gtk_label_new_with_mnemonic (_(" Confirmer"));
  gtk_widget_show (label68);
  gtk_box_pack_start (GTK_BOX (hbox26), label68, FALSE, FALSE, 0);

  alibouaine_checkbutton10 = gtk_check_button_new_with_mnemonic (_("Carte bancaire"));
  gtk_widget_show (alibouaine_checkbutton10);
  gtk_fixed_put (GTK_FIXED (alibouaine_fixed10), alibouaine_checkbutton10, 488, 264);
  gtk_widget_set_size_request (alibouaine_checkbutton10, 126, 24);

  alibouaine_checkbutton9 = gtk_check_button_new_with_mnemonic (_("Esp\303\250ces"));
  gtk_widget_show (alibouaine_checkbutton9);
  gtk_fixed_put (GTK_FIXED (alibouaine_fixed10), alibouaine_checkbutton9, 288, 264);
  gtk_widget_set_size_request (alibouaine_checkbutton9, 118, 24);

  alibouaine_label31 = gtk_label_new (_("Ajouter un service"));
  gtk_widget_show (alibouaine_label31);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (alibouaine_notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (alibouaine_notebook1), 0), alibouaine_label31);

  alibouaine_fixed11 = gtk_fixed_new ();
  gtk_widget_show (alibouaine_fixed11);
  gtk_container_add (GTK_CONTAINER (alibouaine_notebook1), alibouaine_fixed11);

  alibouaine_spinbutton4_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  alibouaine_spinbutton4 = gtk_spin_button_new (GTK_ADJUSTMENT (alibouaine_spinbutton4_adj), 1, 0);
  gtk_widget_show (alibouaine_spinbutton4);
  gtk_fixed_put (GTK_FIXED (alibouaine_fixed11), alibouaine_spinbutton4, 224, 80);
  gtk_widget_set_size_request (alibouaine_spinbutton4, 152, 27);

  alibouaine_entry11 = gtk_entry_new ();
  gtk_widget_show (alibouaine_entry11);
  gtk_fixed_put (GTK_FIXED (alibouaine_fixed11), alibouaine_entry11, 224, 136);
  gtk_widget_set_size_request (alibouaine_entry11, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (alibouaine_entry11), 8226);

  alibouaine_entry12 = gtk_entry_new ();
  gtk_widget_show (alibouaine_entry12);
  gtk_fixed_put (GTK_FIXED (alibouaine_fixed11), alibouaine_entry12, 224, 200);
  gtk_widget_set_size_request (alibouaine_entry12, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (alibouaine_entry12), 8226);

  alibouaine_label42 = gtk_label_new (_("<span color=\"LIGHTSEAGREEN\"font='11'weight='bold'>Le nouveau prix \n    (en dinars) :</span>"));
  gtk_widget_show (alibouaine_label42);
  gtk_fixed_put (GTK_FIXED (alibouaine_fixed11), alibouaine_label42, 16, 200);
  gtk_widget_set_size_request (alibouaine_label42, 136, 32);
  gtk_label_set_use_markup (GTK_LABEL (alibouaine_label42), TRUE);

  alibouaine_label43 = gtk_label_new (_("<span color=\"LIGHTSEAGREEN\"font='11'weight='bold'>Les modes de paiement\n        disponibles  :</span>"));
  gtk_widget_show (alibouaine_label43);
  gtk_fixed_put (GTK_FIXED (alibouaine_fixed11), alibouaine_label43, 0, 264);
  gtk_widget_set_size_request (alibouaine_label43, 176, 40);
  gtk_label_set_use_markup (GTK_LABEL (alibouaine_label43), TRUE);

  alibouaine_label52 = gtk_label_new (_("<span foreground=\"#900000\"\nfont_desc=\"bold 15\"\nvariant=\"smallcaps\"> Modifier un service : </span>"));
  gtk_widget_show (alibouaine_label52);
  gtk_fixed_put (GTK_FIXED (alibouaine_fixed11), alibouaine_label52, 224, 16);
  gtk_widget_set_size_request (alibouaine_label52, 288, 25);
  gtk_label_set_use_markup (GTK_LABEL (alibouaine_label52), TRUE);

  image23 = create_pixmap (Services, "index.png");
  gtk_widget_show (image23);
  gtk_fixed_put (GTK_FIXED (alibouaine_fixed11), image23, 544, 8);
  gtk_widget_set_size_request (image23, 72, 56);
  gtk_misc_set_alignment (GTK_MISC (image23), 0.71, 0.71);

  image27 = create_pixmap (Services, "tn.png");
  gtk_widget_show (image27);
  gtk_fixed_put (GTK_FIXED (alibouaine_fixed11), image27, 48, 8);
  gtk_widget_set_size_request (image27, 64, 56);
  gtk_misc_set_alignment (GTK_MISC (image27), 0.5, 0);

  alibouaine_label41 = gtk_label_new (_("<span color=\"LIGHTSEAGREEN\"font='11'weight='bold'>Le nouveau nom\n    du service :</span>"));
  gtk_widget_show (alibouaine_label41);
  gtk_fixed_put (GTK_FIXED (alibouaine_fixed11), alibouaine_label41, 8, 136);
  gtk_widget_set_size_request (alibouaine_label41, 152, 32);
  gtk_label_set_use_markup (GTK_LABEL (alibouaine_label41), TRUE);

  alibouaine_label40 = gtk_label_new (_("<span color=\"LIGHTSEAGREEN\"font='11'weight='bold'>Id service :</span>"));
  gtk_widget_show (alibouaine_label40);
  gtk_fixed_put (GTK_FIXED (alibouaine_fixed11), alibouaine_label40, 48, 88);
  gtk_widget_set_size_request (alibouaine_label40, 80, 16);
  gtk_label_set_use_markup (GTK_LABEL (alibouaine_label40), TRUE);

  ali_button4 = gtk_button_new ();
  gtk_widget_show (ali_button4);
  gtk_fixed_put (GTK_FIXED (alibouaine_fixed11), ali_button4, 552, 336);
  gtk_widget_set_size_request (ali_button4, 114, 29);

  alignment27 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment27);
  gtk_container_add (GTK_CONTAINER (ali_button4), alignment27);

  hbox27 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox27);
  gtk_container_add (GTK_CONTAINER (alignment27), hbox27);

  image45 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image45);
  gtk_box_pack_start (GTK_BOX (hbox27), image45, FALSE, FALSE, 0);

  label69 = gtk_label_new_with_mnemonic (_(" Confirmer"));
  gtk_widget_show (label69);
  gtk_box_pack_start (GTK_BOX (hbox27), label69, FALSE, FALSE, 0);

  alibouaine_checkbutton12 = gtk_check_button_new_with_mnemonic (_("Carte bancaire"));
  gtk_widget_show (alibouaine_checkbutton12);
  gtk_fixed_put (GTK_FIXED (alibouaine_fixed11), alibouaine_checkbutton12, 384, 272);
  gtk_widget_set_size_request (alibouaine_checkbutton12, 126, 24);

  alibouaine_checkbutton11 = gtk_check_button_new_with_mnemonic (_("Esp\303\250ces"));
  gtk_widget_show (alibouaine_checkbutton11);
  gtk_fixed_put (GTK_FIXED (alibouaine_fixed11), alibouaine_checkbutton11, 216, 272);
  gtk_widget_set_size_request (alibouaine_checkbutton11, 126, 24);

  ali_label32 = gtk_label_new (_("Modifier un service"));
  gtk_widget_show (ali_label32);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (alibouaine_notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (alibouaine_notebook1), 1), ali_label32);

  alibouaine_fixed13 = gtk_fixed_new ();
  gtk_widget_show (alibouaine_fixed13);
  gtk_container_add (GTK_CONTAINER (alibouaine_notebook1), alibouaine_fixed13);

  alibouaine_spinbutton5_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  alibouaine_spinbutton5 = gtk_spin_button_new (GTK_ADJUSTMENT (alibouaine_spinbutton5_adj), 1, 0);
  gtk_widget_show (alibouaine_spinbutton5);
  gtk_fixed_put (GTK_FIXED (alibouaine_fixed13), alibouaine_spinbutton5, 312, 104);
  gtk_widget_set_size_request (alibouaine_spinbutton5, 112, 27);

  image22 = create_pixmap (Services, "index.png");
  gtk_widget_show (image22);
  gtk_fixed_put (GTK_FIXED (alibouaine_fixed13), image22, 544, 8);
  gtk_widget_set_size_request (image22, 72, 56);
  gtk_misc_set_alignment (GTK_MISC (image22), 0.71, 0.71);

  image26 = create_pixmap (Services, "tn.png");
  gtk_widget_show (image26);
  gtk_fixed_put (GTK_FIXED (alibouaine_fixed13), image26, 32, 8);
  gtk_widget_set_size_request (image26, 64, 56);
  gtk_misc_set_alignment (GTK_MISC (image26), 0.5, 0);

  alibouaine_label53 = gtk_label_new (_("<span foreground=\"#900000\"\nfont_desc=\"bold 15\"\nvariant=\"smallcaps\">Supprimmer un service : </span>"));
  gtk_widget_show (alibouaine_label53);
  gtk_fixed_put (GTK_FIXED (alibouaine_fixed13), alibouaine_label53, 208, 24);
  gtk_widget_set_size_request (alibouaine_label53, 264, 24);
  gtk_label_set_use_markup (GTK_LABEL (alibouaine_label53), TRUE);

  alibouaine_label44 = gtk_label_new (_("<span color=\"LIGHTSEAGREEN\"font='11'weight='bold'>Id service :</span>"));
  gtk_widget_show (alibouaine_label44);
  gtk_fixed_put (GTK_FIXED (alibouaine_fixed13), alibouaine_label44, 192, 104);
  gtk_widget_set_size_request (alibouaine_label44, 96, 24);
  gtk_label_set_use_markup (GTK_LABEL (alibouaine_label44), TRUE);

  ali_label71 = gtk_label_new (_("label71"));
  gtk_widget_show (ali_label71);
  gtk_fixed_put (GTK_FIXED (alibouaine_fixed13), ali_label71, 208, 168);
  gtk_widget_set_size_request (ali_label71, 225, 17);

  alibouaine_button17 = gtk_button_new ();
  gtk_widget_show (alibouaine_button17);
  gtk_fixed_put (GTK_FIXED (alibouaine_fixed13), alibouaine_button17, 448, 208);
  gtk_widget_set_size_request (alibouaine_button17, 104, 29);

  alignment7 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment7);
  gtk_container_add (GTK_CONTAINER (alibouaine_button17), alignment7);

  hbox7 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox7);
  gtk_container_add (GTK_CONTAINER (alignment7), hbox7);

  image12 = gtk_image_new_from_stock ("gtk-delete", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image12);
  gtk_box_pack_start (GTK_BOX (hbox7), image12, FALSE, FALSE, 0);

  label45 = gtk_label_new_with_mnemonic (_(" Supprimer "));
  gtk_widget_show (label45);
  gtk_box_pack_start (GTK_BOX (hbox7), label45, FALSE, FALSE, 0);

  alibouaine_label33 = gtk_label_new (_("Supprimer un service"));
  gtk_widget_show (alibouaine_label33);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (alibouaine_notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (alibouaine_notebook1), 2), alibouaine_label33);

  alibouaine_fixed12 = gtk_fixed_new ();
  gtk_widget_show (alibouaine_fixed12);
  gtk_container_add (GTK_CONTAINER (alibouaine_notebook1), alibouaine_fixed12);

  alibouaine_treeview1 = gtk_tree_view_new ();
  gtk_widget_show (alibouaine_treeview1);
  gtk_fixed_put (GTK_FIXED (alibouaine_fixed12), alibouaine_treeview1, 192, 112);
  gtk_widget_set_size_request (alibouaine_treeview1, 300, 200);

  image21 = create_pixmap (Services, "index.png");
  gtk_widget_show (image21);
  gtk_fixed_put (GTK_FIXED (alibouaine_fixed12), image21, 544, 8);
  gtk_widget_set_size_request (image21, 72, 56);
  gtk_misc_set_alignment (GTK_MISC (image21), 0.71, 0.71);

  image25 = create_pixmap (Services, "tn.png");
  gtk_widget_show (image25);
  gtk_fixed_put (GTK_FIXED (alibouaine_fixed12), image25, 32, 8);
  gtk_widget_set_size_request (image25, 64, 56);
  gtk_misc_set_alignment (GTK_MISC (image25), 0.5, 0);

  alibouaine_label46 = gtk_label_new (_("<span foreground=\"#900000\"\nfont_desc=\"bold 15\"\nvariant=\"smallcaps\">Les services disponibles : </span>"));
  gtk_widget_show (alibouaine_label46);
  gtk_fixed_put (GTK_FIXED (alibouaine_fixed12), alibouaine_label46, 184, 16);
  gtk_widget_set_size_request (alibouaine_label46, 281, 32);
  gtk_label_set_use_markup (GTK_LABEL (alibouaine_label46), TRUE);

  ali_button5 = gtk_button_new ();
  gtk_widget_show (ali_button5);
  gtk_fixed_put (GTK_FIXED (alibouaine_fixed12), ali_button5, 560, 336);
  gtk_widget_set_size_request (ali_button5, 90, 29);

  alignment28 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment28);
  gtk_container_add (GTK_CONTAINER (ali_button5), alignment28);

  hbox28 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox28);
  gtk_container_add (GTK_CONTAINER (alignment28), hbox28);

  image46 = gtk_image_new_from_stock ("gtk-sort-ascending", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image46);
  gtk_box_pack_start (GTK_BOX (hbox28), image46, FALSE, FALSE, 0);

  label70 = gtk_label_new_with_mnemonic (_(" Afficher"));
  gtk_widget_show (label70);
  gtk_box_pack_start (GTK_BOX (hbox28), label70, FALSE, FALSE, 0);

  alibouaine_abel34 = gtk_label_new (_("Afficher un service"));
  gtk_widget_show (alibouaine_abel34);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (alibouaine_notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (alibouaine_notebook1), 3), alibouaine_abel34);

  alibouaine_fixed14 = gtk_fixed_new ();
  gtk_widget_show (alibouaine_fixed14);
  gtk_container_add (GTK_CONTAINER (alibouaine_notebook1), alibouaine_fixed14);

  alibouaine_combobox2 = gtk_combo_box_new_text ();
  gtk_widget_show (alibouaine_combobox2);
  gtk_fixed_put (GTK_FIXED (alibouaine_fixed14), alibouaine_combobox2, 193, 88);
  gtk_widget_set_size_request (alibouaine_combobox2, 180, 31);

  alibouaine_spinbutton6_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  alibouaine_spinbutton6 = gtk_spin_button_new (GTK_ADJUSTMENT (alibouaine_spinbutton6_adj), 1, 0);
  gtk_widget_show (alibouaine_spinbutton6);
  gtk_fixed_put (GTK_FIXED (alibouaine_fixed14), alibouaine_spinbutton6, 200, 232);
  gtk_widget_set_size_request (alibouaine_spinbutton6, 60, 27);

  alibouaine_textview2 = gtk_text_view_new ();
  gtk_widget_show (alibouaine_textview2);
  gtk_fixed_put (GTK_FIXED (alibouaine_fixed14), alibouaine_textview2, 200, 160);
  gtk_widget_set_size_request (alibouaine_textview2, 160, 34);

  alibouaine_label48 = gtk_label_new (_("<span color=\"LIGHTSEAGREEN\"font='11'weight='bold'>Le service\n demand\303\251 :</span>"));
  gtk_widget_show (alibouaine_label48);
  gtk_fixed_put (GTK_FIXED (alibouaine_fixed14), alibouaine_label48, 24, 232);
  gtk_widget_set_size_request (alibouaine_label48, 144, 32);
  gtk_label_set_use_markup (GTK_LABEL (alibouaine_label48), TRUE);

  alibouaine_label50 = gtk_label_new (_("<span color=\"LIGHTSEAGREEN\"font='11'weight='bold'>Les r\303\251servations\n          sont :</span>"));
  gtk_widget_show (alibouaine_label50);
  gtk_fixed_put (GTK_FIXED (alibouaine_fixed14), alibouaine_label50, 24, 160);
  gtk_widget_set_size_request (alibouaine_label50, 128, 32);
  gtk_label_set_use_markup (GTK_LABEL (alibouaine_label50), TRUE);

  alibouaine_label54 = gtk_label_new (_("<span foreground=\"#900000\"\nfont_desc=\"bold 15\"\nvariant=\"smallcaps\">Affecter un service : </span>"));
  gtk_widget_show (alibouaine_label54);
  gtk_fixed_put (GTK_FIXED (alibouaine_fixed14), alibouaine_label54, 200, 24);
  gtk_widget_set_size_request (alibouaine_label54, 232, 24);
  gtk_label_set_use_markup (GTK_LABEL (alibouaine_label54), TRUE);

  alibouaine_label47 = gtk_label_new (_("<span color=\"LIGHTSEAGREEN\"font='11'weight='bold'>Id r\303\251servation :</span>"));
  gtk_widget_show (alibouaine_label47);
  gtk_fixed_put (GTK_FIXED (alibouaine_fixed14), alibouaine_label47, 32, 88);
  gtk_widget_set_size_request (alibouaine_label47, 121, 25);
  gtk_label_set_use_markup (GTK_LABEL (alibouaine_label47), TRUE);

  image19 = create_pixmap (Services, "index.png");
  gtk_widget_show (image19);
  gtk_fixed_put (GTK_FIXED (alibouaine_fixed14), image19, 544, 8);
  gtk_widget_set_size_request (image19, 72, 56);
  gtk_misc_set_alignment (GTK_MISC (image19), 0.71, 0.71);

  image20 = create_pixmap (Services, "tn.png");
  gtk_widget_show (image20);
  gtk_fixed_put (GTK_FIXED (alibouaine_fixed14), image20, 32, 8);
  gtk_widget_set_size_request (image20, 64, 56);
  gtk_misc_set_alignment (GTK_MISC (image20), 0.5, 0);

  ali_button18 = gtk_button_new ();
  gtk_widget_show (ali_button18);
  gtk_fixed_put (GTK_FIXED (alibouaine_fixed14), ali_button18, 400, 288);
  gtk_widget_set_size_request (ali_button18, 96, 32);

  alignment8 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment8);
  gtk_container_add (GTK_CONTAINER (ali_button18), alignment8);

  hbox8 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox8);
  gtk_container_add (GTK_CONTAINER (alignment8), hbox8);

  image13 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image13);
  gtk_box_pack_start (GTK_BOX (hbox8), image13, FALSE, FALSE, 0);

  label49 = gtk_label_new_with_mnemonic (_("Affecter"));
  gtk_widget_show (label49);
  gtk_box_pack_start (GTK_BOX (hbox8), label49, FALSE, FALSE, 0);

  alibouaine_label35 = gtk_label_new (_("Affecter un service"));
  gtk_widget_show (alibouaine_label35);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (alibouaine_notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (alibouaine_notebook1), 4), alibouaine_label35);

  g_signal_connect ((gpointer) ali_button3, "clicked",
                    G_CALLBACK (on_ali_button3_clicked),
                    NULL);
  g_signal_connect ((gpointer) alibouaine_checkbutton10, "toggled",
                    G_CALLBACK (on_alibouaine_checkbutton10_toggled),
                    NULL);
  g_signal_connect ((gpointer) alibouaine_checkbutton9, "toggled",
                    G_CALLBACK (on_alibouaine_checkbutton9_toggled),
                    NULL);
  g_signal_connect ((gpointer) ali_button4, "clicked",
                    G_CALLBACK (on_ali_button4_clicked),
                    NULL);
  g_signal_connect ((gpointer) alibouaine_checkbutton12, "toggled",
                    G_CALLBACK (on_alibouaine_checkbutton12_toggled),
                    NULL);
  g_signal_connect ((gpointer) alibouaine_checkbutton11, "toggled",
                    G_CALLBACK (on_alibouaine_checkbutton11_toggled),
                    NULL);
  g_signal_connect ((gpointer) alibouaine_button17, "clicked",
                    G_CALLBACK (on_alibouaine_button17_clicked),
                    NULL);
  g_signal_connect ((gpointer) alibouaine_treeview1, "row_activated",
                    G_CALLBACK (on_alibouaine_treeview1_row_activated),
                    NULL);
  g_signal_connect ((gpointer) ali_button5, "clicked",
                    G_CALLBACK (on_ali_button5_clicked),
                    NULL);
  g_signal_connect ((gpointer) ali_button18, "clicked",
                    G_CALLBACK (on_ali_button18_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (Services, Services, "Services");
  GLADE_HOOKUP_OBJECT (Services, alibouaine_notebook1, "alibouaine_notebook1");
  GLADE_HOOKUP_OBJECT (Services, alibouaine_fixed10, "alibouaine_fixed10");
  GLADE_HOOKUP_OBJECT (Services, alibouaine_entry9, "alibouaine_entry9");
  GLADE_HOOKUP_OBJECT (Services, alibouaine_entry10, "alibouaine_entry10");
  GLADE_HOOKUP_OBJECT (Services, alibouaine_label38, "alibouaine_label38");
  GLADE_HOOKUP_OBJECT (Services, alibouaine_label39, "alibouaine_label39");
  GLADE_HOOKUP_OBJECT (Services, image24, "image24");
  GLADE_HOOKUP_OBJECT (Services, image28, "image28");
  GLADE_HOOKUP_OBJECT (Services, alibouaine_label51, "alibouaine_label51");
  GLADE_HOOKUP_OBJECT (Services, alibouaine_label36, "alibouaine_label36");
  GLADE_HOOKUP_OBJECT (Services, alibouaine_label37, "alibouaine_label37");
  GLADE_HOOKUP_OBJECT (Services, spinbutton1_ali, "spinbutton1_ali");
  GLADE_HOOKUP_OBJECT (Services, ali_button3, "ali_button3");
  GLADE_HOOKUP_OBJECT (Services, alignment26, "alignment26");
  GLADE_HOOKUP_OBJECT (Services, hbox26, "hbox26");
  GLADE_HOOKUP_OBJECT (Services, image44, "image44");
  GLADE_HOOKUP_OBJECT (Services, label68, "label68");
  GLADE_HOOKUP_OBJECT (Services, alibouaine_checkbutton10, "alibouaine_checkbutton10");
  GLADE_HOOKUP_OBJECT (Services, alibouaine_checkbutton9, "alibouaine_checkbutton9");
  GLADE_HOOKUP_OBJECT (Services, alibouaine_label31, "alibouaine_label31");
  GLADE_HOOKUP_OBJECT (Services, alibouaine_fixed11, "alibouaine_fixed11");
  GLADE_HOOKUP_OBJECT (Services, alibouaine_spinbutton4, "alibouaine_spinbutton4");
  GLADE_HOOKUP_OBJECT (Services, alibouaine_entry11, "alibouaine_entry11");
  GLADE_HOOKUP_OBJECT (Services, alibouaine_entry12, "alibouaine_entry12");
  GLADE_HOOKUP_OBJECT (Services, alibouaine_label42, "alibouaine_label42");
  GLADE_HOOKUP_OBJECT (Services, alibouaine_label43, "alibouaine_label43");
  GLADE_HOOKUP_OBJECT (Services, alibouaine_label52, "alibouaine_label52");
  GLADE_HOOKUP_OBJECT (Services, image23, "image23");
  GLADE_HOOKUP_OBJECT (Services, image27, "image27");
  GLADE_HOOKUP_OBJECT (Services, alibouaine_label41, "alibouaine_label41");
  GLADE_HOOKUP_OBJECT (Services, alibouaine_label40, "alibouaine_label40");
  GLADE_HOOKUP_OBJECT (Services, ali_button4, "ali_button4");
  GLADE_HOOKUP_OBJECT (Services, alignment27, "alignment27");
  GLADE_HOOKUP_OBJECT (Services, hbox27, "hbox27");
  GLADE_HOOKUP_OBJECT (Services, image45, "image45");
  GLADE_HOOKUP_OBJECT (Services, label69, "label69");
  GLADE_HOOKUP_OBJECT (Services, alibouaine_checkbutton12, "alibouaine_checkbutton12");
  GLADE_HOOKUP_OBJECT (Services, alibouaine_checkbutton11, "alibouaine_checkbutton11");
  GLADE_HOOKUP_OBJECT (Services, ali_label32, "ali_label32");
  GLADE_HOOKUP_OBJECT (Services, alibouaine_fixed13, "alibouaine_fixed13");
  GLADE_HOOKUP_OBJECT (Services, alibouaine_spinbutton5, "alibouaine_spinbutton5");
  GLADE_HOOKUP_OBJECT (Services, image22, "image22");
  GLADE_HOOKUP_OBJECT (Services, image26, "image26");
  GLADE_HOOKUP_OBJECT (Services, alibouaine_label53, "alibouaine_label53");
  GLADE_HOOKUP_OBJECT (Services, alibouaine_label44, "alibouaine_label44");
  GLADE_HOOKUP_OBJECT (Services, ali_label71, "ali_label71");
  GLADE_HOOKUP_OBJECT (Services, alibouaine_button17, "alibouaine_button17");
  GLADE_HOOKUP_OBJECT (Services, alignment7, "alignment7");
  GLADE_HOOKUP_OBJECT (Services, hbox7, "hbox7");
  GLADE_HOOKUP_OBJECT (Services, image12, "image12");
  GLADE_HOOKUP_OBJECT (Services, label45, "label45");
  GLADE_HOOKUP_OBJECT (Services, alibouaine_label33, "alibouaine_label33");
  GLADE_HOOKUP_OBJECT (Services, alibouaine_fixed12, "alibouaine_fixed12");
  GLADE_HOOKUP_OBJECT (Services, alibouaine_treeview1, "alibouaine_treeview1");
  GLADE_HOOKUP_OBJECT (Services, image21, "image21");
  GLADE_HOOKUP_OBJECT (Services, image25, "image25");
  GLADE_HOOKUP_OBJECT (Services, alibouaine_label46, "alibouaine_label46");
  GLADE_HOOKUP_OBJECT (Services, ali_button5, "ali_button5");
  GLADE_HOOKUP_OBJECT (Services, alignment28, "alignment28");
  GLADE_HOOKUP_OBJECT (Services, hbox28, "hbox28");
  GLADE_HOOKUP_OBJECT (Services, image46, "image46");
  GLADE_HOOKUP_OBJECT (Services, label70, "label70");
  GLADE_HOOKUP_OBJECT (Services, alibouaine_abel34, "alibouaine_abel34");
  GLADE_HOOKUP_OBJECT (Services, alibouaine_fixed14, "alibouaine_fixed14");
  GLADE_HOOKUP_OBJECT (Services, alibouaine_combobox2, "alibouaine_combobox2");
  GLADE_HOOKUP_OBJECT (Services, alibouaine_spinbutton6, "alibouaine_spinbutton6");
  GLADE_HOOKUP_OBJECT (Services, alibouaine_textview2, "alibouaine_textview2");
  GLADE_HOOKUP_OBJECT (Services, alibouaine_label48, "alibouaine_label48");
  GLADE_HOOKUP_OBJECT (Services, alibouaine_label50, "alibouaine_label50");
  GLADE_HOOKUP_OBJECT (Services, alibouaine_label54, "alibouaine_label54");
  GLADE_HOOKUP_OBJECT (Services, alibouaine_label47, "alibouaine_label47");
  GLADE_HOOKUP_OBJECT (Services, image19, "image19");
  GLADE_HOOKUP_OBJECT (Services, image20, "image20");
  GLADE_HOOKUP_OBJECT (Services, ali_button18, "ali_button18");
  GLADE_HOOKUP_OBJECT (Services, alignment8, "alignment8");
  GLADE_HOOKUP_OBJECT (Services, hbox8, "hbox8");
  GLADE_HOOKUP_OBJECT (Services, image13, "image13");
  GLADE_HOOKUP_OBJECT (Services, label49, "label49");
  GLADE_HOOKUP_OBJECT (Services, alibouaine_label35, "alibouaine_label35");

  return Services;
}

GtkWidget*
create_Espace_citoyen (void)
{
  GtkWidget *Espace_citoyen;
  GtkWidget *alibouaine_fixed10;
  GtkWidget *image31;
  GtkWidget *image34;
  GtkWidget *alibouaine_button17;
  GtkWidget *alignment19;
  GtkWidget *hbox19;
  GtkWidget *image30;
  GtkWidget *label58;
  GtkWidget *alibouaine_button18;
  GtkWidget *alignment20;
  GtkWidget *hbox20;
  GtkWidget *image32;
  GtkWidget *label59;
  GtkWidget *alibouaine_button19;
  GtkWidget *alignment21;
  GtkWidget *hbox21;
  GtkWidget *image33;
  GtkWidget *label60;
  GtkWidget *alibouaine_label57;

  Espace_citoyen = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (Espace_citoyen), _("Espace_citoyen"));

  alibouaine_fixed10 = gtk_fixed_new ();
  gtk_widget_show (alibouaine_fixed10);
  gtk_container_add (GTK_CONTAINER (Espace_citoyen), alibouaine_fixed10);

  image31 = create_pixmap (Espace_citoyen, "tn.png");
  gtk_widget_show (image31);
  gtk_fixed_put (GTK_FIXED (alibouaine_fixed10), image31, 8, 16);
  gtk_widget_set_size_request (image31, 64, 56);
  gtk_misc_set_alignment (GTK_MISC (image31), 0.5, 0);

  image34 = create_pixmap (Espace_citoyen, "index.png");
  gtk_widget_show (image34);
  gtk_fixed_put (GTK_FIXED (alibouaine_fixed10), image34, 368, 16);
  gtk_widget_set_size_request (image34, 72, 56);
  gtk_misc_set_alignment (GTK_MISC (image34), 0.71, 0.71);

  alibouaine_button17 = gtk_button_new ();
  gtk_widget_show (alibouaine_button17);
  gtk_fixed_put (GTK_FIXED (alibouaine_fixed10), alibouaine_button17, 96, 96);
  gtk_widget_set_size_request (alibouaine_button17, 248, 32);

  alignment19 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment19);
  gtk_container_add (GTK_CONTAINER (alibouaine_button17), alignment19);

  hbox19 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox19);
  gtk_container_add (GTK_CONTAINER (alignment19), hbox19);

  image30 = gtk_image_new_from_stock ("gtk-orientation-landscape", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image30);
  gtk_box_pack_start (GTK_BOX (hbox19), image30, FALSE, FALSE, 0);

  label58 = gtk_label_new_with_mnemonic (_("  G\303\251rer mon compte"));
  gtk_widget_show (label58);
  gtk_box_pack_start (GTK_BOX (hbox19), label58, FALSE, FALSE, 0);

  alibouaine_button18 = gtk_button_new ();
  gtk_widget_show (alibouaine_button18);
  gtk_fixed_put (GTK_FIXED (alibouaine_fixed10), alibouaine_button18, 96, 152);
  gtk_widget_set_size_request (alibouaine_button18, 248, 32);

  alignment20 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment20);
  gtk_container_add (GTK_CONTAINER (alibouaine_button18), alignment20);

  hbox20 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox20);
  gtk_container_add (GTK_CONTAINER (alignment20), hbox20);

  image32 = gtk_image_new_from_stock ("gtk-index", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image32);
  gtk_box_pack_start (GTK_BOX (hbox20), image32, FALSE, FALSE, 0);

  label59 = gtk_label_new_with_mnemonic (_(" G\303\251rer mes r\303\251servations"));
  gtk_widget_show (label59);
  gtk_box_pack_start (GTK_BOX (hbox20), label59, FALSE, FALSE, 0);

  alibouaine_button19 = gtk_button_new ();
  gtk_widget_show (alibouaine_button19);
  gtk_fixed_put (GTK_FIXED (alibouaine_fixed10), alibouaine_button19, 96, 208);
  gtk_widget_set_size_request (alibouaine_button19, 248, 32);

  alignment21 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment21);
  gtk_container_add (GTK_CONTAINER (alibouaine_button19), alignment21);

  hbox21 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox21);
  gtk_container_add (GTK_CONTAINER (alignment21), hbox21);

  image33 = gtk_image_new_from_stock ("gtk-about", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image33);
  gtk_box_pack_start (GTK_BOX (hbox21), image33, FALSE, FALSE, 0);

  label60 = gtk_label_new_with_mnemonic (_(" G\303\251rer mes avis et r\303\251clamations "));
  gtk_widget_show (label60);
  gtk_box_pack_start (GTK_BOX (hbox21), label60, FALSE, FALSE, 0);

  alibouaine_label57 = gtk_label_new (_("<span foreground=\"#900000\"\nfont_desc=\"bold 15\"\nvariant=\"smallcaps\"> S\303\251l\303\251ctionner votre choix : </span>"));
  gtk_widget_show (alibouaine_label57);
  gtk_fixed_put (GTK_FIXED (alibouaine_fixed10), alibouaine_label57, 80, 32);
  gtk_widget_set_size_request (alibouaine_label57, 264, 25);
  gtk_label_set_use_markup (GTK_LABEL (alibouaine_label57), TRUE);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (Espace_citoyen, Espace_citoyen, "Espace_citoyen");
  GLADE_HOOKUP_OBJECT (Espace_citoyen, alibouaine_fixed10, "alibouaine_fixed10");
  GLADE_HOOKUP_OBJECT (Espace_citoyen, image31, "image31");
  GLADE_HOOKUP_OBJECT (Espace_citoyen, image34, "image34");
  GLADE_HOOKUP_OBJECT (Espace_citoyen, alibouaine_button17, "alibouaine_button17");
  GLADE_HOOKUP_OBJECT (Espace_citoyen, alignment19, "alignment19");
  GLADE_HOOKUP_OBJECT (Espace_citoyen, hbox19, "hbox19");
  GLADE_HOOKUP_OBJECT (Espace_citoyen, image30, "image30");
  GLADE_HOOKUP_OBJECT (Espace_citoyen, label58, "label58");
  GLADE_HOOKUP_OBJECT (Espace_citoyen, alibouaine_button18, "alibouaine_button18");
  GLADE_HOOKUP_OBJECT (Espace_citoyen, alignment20, "alignment20");
  GLADE_HOOKUP_OBJECT (Espace_citoyen, hbox20, "hbox20");
  GLADE_HOOKUP_OBJECT (Espace_citoyen, image32, "image32");
  GLADE_HOOKUP_OBJECT (Espace_citoyen, label59, "label59");
  GLADE_HOOKUP_OBJECT (Espace_citoyen, alibouaine_button19, "alibouaine_button19");
  GLADE_HOOKUP_OBJECT (Espace_citoyen, alignment21, "alignment21");
  GLADE_HOOKUP_OBJECT (Espace_citoyen, hbox21, "hbox21");
  GLADE_HOOKUP_OBJECT (Espace_citoyen, image33, "image33");
  GLADE_HOOKUP_OBJECT (Espace_citoyen, label60, "label60");
  GLADE_HOOKUP_OBJECT (Espace_citoyen, alibouaine_label57, "alibouaine_label57");

  return Espace_citoyen;
}

