/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_User_add (void);
GtkWidget* create_Espace_admin (void);
GtkWidget* create_Sur (void);
GtkWidget* create_Services (void);
GtkWidget* create_Espace_citoyen (void);
